FROM node:17-slim
LABEL maintainer "Alan Lira <alan.lira08@gmail.com>"
WORKDIR /home/node/api
ARG PORT=8000
ENV PORT=$PORT
EXPOSE $PORT
COPY package.json package-lock.json* ./
RUN npm install --no-optional && npm cache clean --force
WORKDIR /home/node/api/src
CMD npm run dev